"""The disclaimer every user-facing output must carry (CLAUDE.md §18).

WHY one constant: the CLI (Phase 5), the report (Phase 7), the API and the
UI (Phase 8) must all carry the same wording. One definition means the
wording can't drift between surfaces.
"""

from typing import Final

DISCLAIMER: Final[str] = (
    "AgentInvest is an experimental research tool. Its output is generated by AI "
    "systems, may contain errors, and is not investment advice. Do not make "
    "investment decisions on the basis of this output."
)
