"""SQLAlchemy ORM models for CLAUDE.md §14's `documents`/`document_chunks`
tables.

WHY only these two tables exist here, not the full §14 list (evidence,
claims, tool_calls, llm_calls, cache, debate_rounds): those get built once
a phase actually needs cross-run Postgres durability for that data (see
ADR-0012, which made the same call for the in-memory Evidence Store) —
Phase 3's exit criterion is retrieval infrastructure, not migrating the
whole schema speculatively ahead of need.

WHY this module is NOT under the `backend.calc`/`backend.evidence`
mypy --strict override: SQLAlchemy's declarative `Mapped[...]` typing
already carries real type information, and strict mode's stricter checks
(e.g. disallowing untyped decorators) fight the ORM's own patterns for
little benefit here, unlike the pure-function code strict mode was
adopted for.
"""

from __future__ import annotations

from datetime import date, datetime
from uuid import UUID, uuid4

from pgvector.sqlalchemy import Vector
from sqlalchemy import Computed, Date, DateTime, ForeignKey, Index, Integer, String, Text
from sqlalchemy.dialects.postgresql import TSVECTOR
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship

from backend.rag.embeddings import EMBEDDING_DIM


class Base(DeclarativeBase):
    pass


class Document(Base):
    """One filing's full stored text — CLAUDE.md §14: "full stored source
    text so quote verification can run offline," the same principle
    backend/evidence/validation.py already applies to XBRL facts, extended
    here to filing text."""

    __tablename__ = "documents"

    id: Mapped[UUID] = mapped_column(primary_key=True, default=uuid4)
    accession: Mapped[str] = mapped_column(String, nullable=False)
    ticker: Mapped[str] = mapped_column(String, nullable=False, index=True)
    form: Mapped[str] = mapped_column(String, nullable=False)
    filing_date: Mapped[date] = mapped_column(Date, nullable=False)
    full_text: Mapped[str] = mapped_column(Text, nullable=False)
    retrieved_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)

    chunks: Mapped[list[DocumentChunk]] = relationship(back_populates="document")

    __table_args__ = (
        # WHY unique: this is indexing.py's idempotency key — re-running
        # indexing for the same accession must not duplicate the stored
        # document (see index_filing's ON CONFLICT DO NOTHING upsert).
        Index("uq_documents_accession", "accession", unique=True),
    )


class DocumentChunk(Base):
    """One chunk of a filing section, with pgvector's HNSW-indexed dense
    embedding plus a generated `tsvector` column for full-text search —
    the two legs backend/rag/retrieval.py's hybrid search fuses via RRF.

    `char_start`/`char_end` are a deliberate, documented addition beyond
    §14's literal `accession`/`item`/`filing_date`/`fiscal_period` metadata
    list — see ADR-0015: without an offset into `Document.full_text`,
    there is no way to do the same verbatim-containment citation check
    `backend/evidence/validation.py` already runs for `xbrl_fact` evidence,
    applied here to chunk-sourced quotes.
    """

    __tablename__ = "document_chunks"

    id: Mapped[UUID] = mapped_column(primary_key=True, default=uuid4)
    document_id: Mapped[UUID] = mapped_column(
        ForeignKey("documents.id", ondelete="CASCADE"), nullable=False
    )
    chunk_index: Mapped[int] = mapped_column(Integer, nullable=False)
    text: Mapped[str] = mapped_column(Text, nullable=False)

    accession: Mapped[str] = mapped_column(String, nullable=False, index=True)
    item: Mapped[str | None] = mapped_column(String, nullable=True)
    filing_date: Mapped[date] = mapped_column(Date, nullable=False)
    fiscal_period: Mapped[str | None] = mapped_column(String, nullable=True)

    char_start: Mapped[int] = mapped_column(Integer, nullable=False)
    char_end: Mapped[int] = mapped_column(Integer, nullable=False)

    embedding: Mapped[list[float]] = mapped_column(Vector(EMBEDDING_DIM), nullable=False)

    # Postgres computes and maintains this column; the exact
    # to_tsvector('english', text) expression is authored explicitly in
    # the Alembic migration (not autogenerated) since it's a decision
    # worth reviewing directly, not inferring from ORM metadata diffing.
    tsv: Mapped[str] = mapped_column(
        TSVECTOR, Computed("to_tsvector('english', text)", persisted=True), nullable=False
    )

    document: Mapped[Document] = relationship(back_populates="chunks")

    __table_args__ = (
        # Idempotency key for indexing.py: same accession + same
        # chunk_index is the same chunk on re-run.
        Index(
            "uq_document_chunks_accession_chunk_index",
            "accession",
            "chunk_index",
            unique=True,
        ),
    )
